winget install 7zip.7zip
winget install Adobe.Acrobat.Reader.32-bit
winget install flux.flux
winget install Melvin-Abraham.Google-Assistant
winget install Google.Chrome
winget install Google.Drive
winget install Google.EarthPro
winget install Greenshot.Greenshot
winget install SourceFoundry.HackFonts
winget install DominikReichl.KeePass
winget install Malwarebytes.Malwarebytes
winget install Microsoft.VisualStudioCode
winget install Mozilla.Firefox
winget install Mozilla.Thunderbird.Beta
winget install clsid2.mpc-hc
winget install Notepad++.Notepad++
winget install PrivateInternetAccess.PrivateInternetAccess
winget install Telerik.Fiddler.Classic
winget install Python.Python.3
winget install c0re100.qBittorrent-Enhanced-Edition
winget install SideQuestVR.SideQuest
winget install Ookla.Speedtest
winget install Twitch.Twitch
winget install Microsoft.PowerToys
